### ISSUE TITLE
depreciated commands in botocore

### ISSUE THREAD

**Issue by zoellner** [awslabs/reinvent2014-scalable-site-management#4]
Thank you for providing the easy_deploy script, very useful!
I noticed there are a few warnings about depreciated functions in the botocore packages. Would be great to update these to keep this script functional. 

> > /Library/Python/2.7/site-packages/botocore/session.py:571: ImminentRemovalWarning: get_service is deprecated and will be removed.  Use create_client instead.
> >   "Use create_client instead.", ImminentRemovalWarning)
> > /Library/Python/2.7/site-packages/botocore/service.py:231: ImminentRemovalWarning: get_service is deprecated and will be removed.  Use Session.create_client instead.
> >   ImminentRemovalWarning)
> > /Library/Python/2.7/site-packages/botocore/service.py:161: ImminentRemovalWarning: get_endpoint is deprecated and will be removed.  Use create_client instead.
> >   "Use create_client instead.", ImminentRemovalWarning)
> > /Library/Python/2.7/site-packages/botocore/service.py:189: ImminentRemovalWarning: get_operation is deprecated and will be removed.  Use create_client instead.
> >   "Use create_client instead.", ImminentRemovalWarning)
> > /Library/Python/2.7/site-packages/botocore/operation.py:105: ImminentRemovalWarning: call() is deprecated and will be removed.  Use clients instead.
> >   "Use clients instead.", ImminentRemovalWarning)

**Comment by jonathanq** [comment]
Merged.  Thanks again for your change!
